from app.models import db, Recipe


# Adds recipes
def seed_recipes():

#Jami

    recipe21 = Recipe(
            title='Tomato Wine (from Soup Production Waste)', description="Making wine is a hobby of mine. I've discovered over the years, that wine can be made out of almost anything.  In this Ingestible, I'll show you how I made a wonderful dry white wine out of tomato soup production waste.", authorId=8, ingredientPhoto='https://content.instructables.com/ORIG/FSA/3CUS/KN8W3OI0/FSA3CUSKN8W3OI0.jpg?auto=webp&frame=1&width=700&height=1024&fit=bounds&md=56a6ec8de5a7f05b68e33474d636d7b5')
    recipe22 = Recipe(
            title='Legend of Zelda Hot Chocolate', description="Put down your boring hot coco powdery hot chocolate and grab your Breath of the Wild Apron, cause we are going to make the best hot chocolate recipe ever! Well, at least the geekiest hot chocolate recipe ever!  This is a Breath of the Wild inspired hot chocolate recipe, full of flavor, savory, chocolaty, totally delicious.  Taste buds be warned. It's gonna be amazing", authorId=7, ingredientPhoto='https://content.instructables.com/ORIG/FI4/416E/KIKA4JZQ/FI4416EKIKA4JZQ.png?auto=webp&frame=1&width=800&fit=bounds&md=e559946e14301f301ec90b7a2da83cdf')
    recipe23 = Recipe(
            title='Rainbow Brownie Ice Cream Sandwiches', description="Rainbows........ Brownies........ Ice cream Sandwiches.......... Excuse me what?!?!?!?!?!  These ice cream sandwiches are so much fun to make and everyone will love them!!! The fudgy brownies are so delicious and rich with a creamy vanilla ice cream balances all the flavours perfectly. Also these are Gluten free!!!!  Plus the multicolour rainbow will brighten anyone's day and celebration. You have beautiful rainbow treats and you can make your own ice cream from scratch!!!  I hope you love these as much as we do!!! Also Happy pride month!!!", authorId=7, ingredientPhoto='https://content.instructables.com/ORIG/FGV/IOIA/KQ57CNYR/FGVIOIAKQ57CNYR.jpg?auto=webp&frame=1&width=525&height=1024&fit=bounds&md=5a1a6a2edd12045de17be38d4263b18b')
    recipe24 = Recipe(
            title='Mourning Buns', description="These flaky creepy confections are made up of apple and puff pasty. They are to die for.", authorId=7, ingredientPhoto='https://content.instructables.com/ORIG/F22/1JRC/KNG1B6DD/F221JRCKNG1B6DD.jpg?auto=webp&frame=1&crop=2:3&width=369&height=1024&fit=bounds&md=3ddeb9d50009eacd751199f4840a0329')
    recipe25 = Recipe(
            title='Creamy Cheese Nuggets', description="Hi everyone! Today we are making these delicious creamy cheese nuggets. If you love Mozzarella sticks or fried mac & cheese balls, this will be an new one to try! These breaded nuggets filled with a combination of stretchy and creamy cheeses.  Mozzarella sticks are great but the problem is that they kind of lack flavor. Mozzarella is such a mild tasting cheese that after it cools down, it is pretty much a tasteless piece of chewy 'meh' cheese...(think cold leftover pizza)  For this recipe, we are going to use multiple kind of cheeses so that it remains creamy even after it cools down to room temperature. The main ingredients of this recipe is cottage cheese. If you had Cheese Manicotti before, you know how creamy and milky the filling is inside those pasta shells. Besides cottage cheese, we also be adding some mozzarella and a little bit of cheddar for a nice yellow color. You could also use different type of stretchy cheeses of your liking, Muenster is highly recommended! We will also be using American cheese slices to make a lovely cheese sauce as the main base ingredients for the nugget to hold it's shape.", authorId=6, ingredientPhoto='https://content.instructables.com/ORIG/F0D/WL8G/KNYM0P7B/F0DWL8GKNYM0P7B.jpg?auto=webp&frame=1&crop=3:2&width=600&height=1024&fit=bounds&md=cba003e684a8166bdd4324bcba1b5d81')
    recipe26 = Recipe(
            title='To Dye for Boozy Deviled Eggs', description="This Easter I wanted to try my hand at Deviled Eggs. My Mom usually makes them, but since I was hosting, I wanted to do my own version  Finding inspiration online for the coloring, and also the varieties of filling, I came up with something of my own using ingredients I had on hand. You can certainly make substitutes depending on what's available to you  They look cute, and have an interesting and wonderful flavor  Nutrition, taste, and uniqueness are all wrapped up into one package with these crowd-pleasing appetizers!", authorId=7, ingredientPhoto='https://content.instructables.com/ORIG/FO2/BLQD/KN36CAG4/FO2BLQDKN36CAG4.jpg?auto=webp&frame=1&width=284&height=1024&fit=bounds&md=1860218b9983ea707694e089851b8e8a')
    recipe27 = Recipe(
            title='Fish-shaped Potato Mash With Tuna', description="Hi! Today we're gonna be making a potato and tuna based fake-fish! I think it is a delicious recipe for a family dinner and a great way to experiment with shapes and food 'sculpture'. No cooking needed, just a mixer and your ability! I hope you'll have fun making it as much as I did :)", authorId=8, ingredientPhoto='https://content.instructables.com/ORIG/FTV/CKP3/KFZEJGHL/FTVCKP3KFZEJGHL.png?auto=webp&frame=1&crop=3:2&width=653&fit=bounds&md=bbfe0506053448f661f25f908e3d562f')
    recipe28 = Recipe(
            title='Diner Style Burger, Fries & Shake at Home', description="Burgers are the absolute best thing on the planet, and what’s the only thing that makes them better? Eating one with a side of salty french fries and washing it down with a super thick milkshake. American diners do this meal combo so well, it's ridiculous! If I could, I'd go to one every week. However, there's just one slight problem. I live in Australia, where diners aren't really a thing. Popping over to America every week to go to a diner seems a little excessive, so I decided to replicate the meal, but also make it accessible for the at home cook  My version of the classic is amped up by baking homemade brioche buns, pickling red onion and mixing together a special burger sauce. I also chose to bake the french fries instead of deep frying them. I figured the mess, huge quantity of oil needed and high heat not worth the effort for something that can easily be achieved in an oven, which isn't as hands on  And finally, we get to the milkshake. My recipe for a chocolate milkshake is so simple but SO good, and the best part is you can make variations of it with other flavours by using vanilla ice-cream and including different flavoured syrups or fruits. I also decided to go one step further and added the can of whipped cream and a maraschino cherry as toppings. Totally indulgent, but completely necessary. We are going for the full diner experience after all!", authorId=6, ingredientPhoto='https://content.instructables.com/ORIG/FHV/WCVP/KAB2MKY8/FHVWCVPKAB2MKY8.png?auto=webp&frame=1&fit=bounds&md=6c2a8ac7f32fcfca87b6d08aba39bbc9')
    recipe29 = Recipe(
            title='Stuffed Red Cherry Tomatoes', description="Stuffed tomatoes are a standard classic French pre-takeaway takeaway and interestingly are slow rather than fast food. Every traiteur and charcuterie has them in season as a ready-made dish to take home and warm up or to be heated up in the shop and eaten as a picnic. Most butchers' shops in France offer a daily, cooked hot dish and stuffed tomatoes à la bonne femme is a a seasonal favourite. I've always thought how interesting it is that many countries, France is just one, maintain this old tradition and link with the past, when people didn't necessarily have ovens in their homes or alternatively wanted a ready-cooked meal without going to a restaurant  Here I'm using cherry tomatoes and these make great hot savouries in a bite sized edition so I guess they should be called 'bon enfant'...maybe  Cherry tomatoes are very easy to grow in a small space in a container or hanging basket. If you have a greenhouse or a window sill you can keep them producing right up to the first frosts. Tomatoes are perennials, so with care you can keep the plants from year to year.", authorId=6, ingredientPhoto='https://content.instructables.com/ORIG/FBO/W3W8/KQQMU174/FBOW3W8KQQMU174.jpg?auto=webp&frame=1&width=799&height=1024&fit=bounds&md=1d1389601c231fbfb3a4ca92f252d1d5')
    recipe30 = Recipe(
            title='Edible Plastic Pouches', description="I have the most amazing life hack for you guys!  Have you ever tried being on a hike and trying to stuff a handful of trail mix into your mouth, hands dirty and all, while dropping way too much of the precious nibbles along the way? Or have you tried letting the kids eat snacks in the car and then found half of it scattered all over the back seat afterwards?  I have the perfect solution! Welcome: edible plastic pouches containing trail mix (or whatever else you like)! They are perfectly pocket-sized and spill-free.  Gone are the days when edible plastic was only a fun and tasteless decorating addition on fancy cakes. Now, this science hack can actually be used for something useful.  The idea behind this edible plastic is actually quite simple. First, we gel water using agar or gelatine, and then, this gel is dehydrated to create an edible, plastic-like sheet that can be used for a variety of purposes.  Sounds good? If you don't care about the nerdy science behind this, go straight to the next step. Otherwise, keep reading.  Agar and gelatine can both be used to solidify a liquid, but they are structurally quite different. Agar is a carbohydrate, and gelatin is a protein. While gelatin is derived from animal collagen, agar comes from algae and is thus plant based (and vegan). Agar melts around 85 degrees C (185 F) whereas gelatin melts at 35 degrees C (95 F), making it less stable. This also means that gelatin will melt in your mouth while agar will not.", authorId=8, ingredientPhoto='https://content.instructables.com/ORIG/F8P/BFEJ/JGGTFZST/F8PBFEJJGGTFZST.jpg?auto=webp&frame=1&width=600&height=1024&fit=bounds&md=f197835c8db3be396cd024837dc19cdb')


    db.session.add(recipe21)
    db.session.add(recipe22)
    db.session.add(recipe23)
    db.session.add(recipe24)
    db.session.add(recipe25)
    db.session.add(recipe26)
    db.session.add(recipe27)
    db.session.add(recipe28)
    db.session.add(recipe29)
    db.session.add(recipe30)


    db.session.commit()


# Uses a raw SQL query to TRUNCATE the users table.
# SQLAlchemy doesn't have a built in function to do this
# TRUNCATE Removes all the data from the table, and RESET IDENTITY
# resets the auto incrementing primary key, CASCADE deletes any
# dependent entities
def undo_recipes():
    db.session.execute('TRUNCATE recipes RESTART IDENTITY CASCADE;')
    db.session.commit()
