"""empty message

Revision ID: 4186065aa798
Revises: 042fbca8a21e
Create Date: 2021-10-14 18:30:29.263575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4186065aa798'
down_revision = '042fbca8a21e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profilePic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profilePic', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
