"""empty message

Revision ID: 1f63a470eb13
Revises: 26ead50599aa
Create Date: 2021-10-11 22:33:02.002666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f63a470eb13'
down_revision = '26ead50599aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('ingredientPhoto', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'ingredientPhoto')
    # ### end Alembic commands ###
