"""empty message

Revision ID: a084305e72eb
Revises: 4186065aa798
Create Date: 2021-10-14 18:30:52.272553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a084305e72eb'
down_revision = '4186065aa798'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profilePic', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profilePic')
    # ### end Alembic commands ###
