"""empty message

Revision ID: fda409190198
Revises: 1f63a470eb13
Create Date: 2021-10-12 13:07:34.500755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fda409190198'
down_revision = '1f63a470eb13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('recipes', sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'time_updated')
    op.drop_column('recipes', 'time_created')
    # ### end Alembic commands ###
